In [16]:
import random
import numpy as np

In [17]:
%precision 3

'%.3f'

In [18]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [19]:
x[:3], y[:3]

([0.524, 0.230, 0.380], [0.978, 0.874, 0.917])

In [20]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[1.502, 1.103, 1.296]

In [21]:
%timeit [x[i] + y[i] for i in range(n)]

10 loops, best of 3: 149 ms per loop


In [22]:
xa = np.array(x)
ya = np.array(y)

In [23]:
xa[:3]

array([ 0.524,  0.23 ,  0.38 ])

In [24]:
za = xa + ya

In [25]:
za[:3]

array([ 1.502,  1.103,  1.296])

In [26]:
%timeit xa + ya

100 loops, best of 3: 2.95 ms per loop


In [27]:
%timeit sum(x)
%timeit np.sum(xa)

100 loops, best of 3: 5.94 ms per loop
1000 loops, best of 3: 686 µs per loop


In [28]:
d = [abs(x[i] - y[i]) for i in range(1000)]
d[:3]

[0.454, 0.644, 0.537]

In [29]:
da = np.abs(xa[:1000, None] - ya[:1000])
da

array([[ 0.454,  0.349,  0.393, ...,  0.032,  0.452,  0.199],
       [ 0.748,  0.644,  0.687, ...,  0.326,  0.747,  0.493],
       [ 0.598,  0.494,  0.537, ...,  0.176,  0.597,  0.343],
       ..., 
       [ 0.158,  0.054,  0.097, ...,  0.264,  0.157,  0.096],
       [ 0.713,  0.609,  0.652, ...,  0.291,  0.712,  0.458],
       [ 0.761,  0.657,  0.7  , ...,  0.339,  0.76 ,  0.506]])