In [1]:
import random
import numpy as np

In [2]:
%precision 3

'%.3f'

In [3]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [4]:
x[:3], y[:3]

([0.045, 0.205, 0.317], [0.067, 0.737, 0.690])

In [5]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[0.111, 0.942, 1.007]

In [6]:
%timeit [x[i] + y[i] for i in range(n)]

10 loops, best of 3: 143 ms per loop


In [7]:
xa = np.array(x)
ya = np.array(y)

In [8]:
xa[:3]

array([ 0.045,  0.205,  0.317])

In [9]:
za = xa + ya

In [10]:
za[:3]

array([ 0.111,  0.942,  1.007])

In [11]:
%timeit xa + ya

100 loops, best of 3: 2.95 ms per loop


In [12]:
%timeit sum(x)
%timeit np.sum(xa)

100 loops, best of 3: 5.99 ms per loop
1000 loops, best of 3: 730 µs per loop


In [13]:
d = [abs(x[i] - y[i]) for i in range(1000)]
d[:3]

[0.022, 0.532, 0.373]

In [14]:
da = np.abs(xa[:1000, None] - ya[:1000])
da

array([[ 0.022,  0.693,  0.645, ...,  0.341,  0.512,  0.656],
       [ 0.138,  0.532,  0.485, ...,  0.181,  0.351,  0.495],
       [ 0.25 ,  0.421,  0.373, ...,  0.069,  0.24 ,  0.384],
       ..., 
       [ 0.126,  0.544,  0.497, ...,  0.193,  0.363,  0.507],
       [ 0.104,  0.566,  0.519, ...,  0.215,  0.385,  0.529],
       [ 0.613,  0.057,  0.01 , ...,  0.294,  0.124,  0.02 ]])